apiVersion: v1
kind: ConfigMap
metadata:
  name: feedbackhub-config
data:
  PORT: "3000"
  MODE: "PROD"
  URL: "https://feedbackhub.example.com"
  DEV_URL: "http://localhost:3000"
  IMAGES_PATH: "assets/images"
  ASSETS_PATH: "assets"
  PRISMA_DB_PUSH: "false"
  API_UPSTREAM: "http://feedbackhub-server:3000"
